### ISSUE TITLE
How do we update the bot engines?  With the new Infrastructure?

### ISSUE THREAD

**Issue by prastle** [triplea-game/infrastructure#29] opened 2018-04-21 18:40 UTC
since this command doesn't work any longer.  As root.
 bash <(curl https://raw.githubusercontent.com/triplea-game/lobby/master/setup_bot) 1.9.0.0.10148 TOKYO_JP 601 4

And previous commands

Also it is interesting that it still asks for a triplea password which doesn't work even when you join with ssh to a bot host.  HELP!

**Comment by prastle** [comment] 2018-04-23 21:56
Bump @DanVanAtta

**Comment by DanVanAtta** [comment] 2018-04-24 00:27
```
bash <(curl https://raw.githubusercontent.com/triplea-game/lobby/master/setup_bot) 1.9.0.0.10148 TOKYO_JP 601 4
```
That would probably still work, but i'm really not sure what state that would leave the machine in. Please do not use any of the lobby scripts anymore, they're all deprecated now; I should have made that clear sooner.

> Also it is interesting that it still asks for a triplea password which doesn't work even when you join with ssh to a bot host. HELP!

This does mean that you're not passing your public key on ssh login attempts. Some machines only find a default 'id_rsa.pub' file, and if not named that then none is used, others will try all available public keys, and some other machines try no keys at all. In your putty client you *must* specify your public key file if you are being prompted for password. TripleA user AFAIK does not have a passsword on it anymore. Eventually I'd like to remove that from root user too.

> How do we update the bot engines?

For the moment I would not update them; they should track with the latest release, not latest prerelease. It should not be standard practice for us to add new map features and update bots to use them. It's an example IMO of us working around our compatibility problems, cheating, rather than doing the infrastructure work so we could support that use-case without causing errors on one version or another of a game client.

Regardless, to answer your question finally, you change the version number variable in this file: https://github.com/triplea-game/infrastructure/blob/master/roles/host_control.sh

Once updated to master all machines will see the updates within 5 minutes. For now we need to manually restart bots after that, I plan to add a feature to infrastructure that applications would restart when a new version is installed.

**Comment by prastle** [comment] 2018-04-24 01:12
ok ty.  But to clarify about triplea login I am login with triplea  user as ssh then is allows me to do stuff ...  then it asks for triplea user password ... which it shouldn't if already ssh login...  Either way unless i am incorrect we should no longer have to use triplea user at all right?

**Comment by prastle** [comment] 2018-04-24 01:24
Also to clarify
My sudo is only for forum doesn't work in bots just my ssh root

**Comment by prastle** [comment] 2018-04-24 01:25
and my  old warclub ssh

**Comment by prastle** [comment] 2018-04-24 01:34
I did try triplea with no password as well btw.  It was only after i entered a valid command  (logged in ssh as triplea and as prastle) that it again asked for the triplea password. Neither old or blank or my ssh password worked btw.  @DanVanAtta

**Comment by prastle** [comment] 2018-04-24 05:04
Well Most of what i was running concerned attempting to update a bot server to the new engine using the above script.  As root and as triplea user and as prastle.  I guess i can test to see what other ones still no longer work.

**Comment by prastle** [comment] 2018-04-24 05:12
@DanVanAtta 

Using username "triplea".
Authenticating with public key "ed25519-key-20180416"
Passphrase for key "ed25519-key-20180416":
Last login: Sat Apr 21 13:45:09 2018 from 24.53.234.237
triplea@bot55_london_uk:~$ ls
bots            restart_bot_02  start_all     start_bot_04  stop_bot_03
maps            restart_bot_03  start_bot_01  stop_all      stop_bot_04
restart_all     restart_bot_04  start_bot_02  stop_bot_01   triplea
restart_bot_01  secrets         start_bot_03  stop_bot_02
triplea@bot55_london_uk:~$ sudo service triplea-bot54 status
[sudo] password for triplea:

**Comment by DanVanAtta** [comment] 2018-04-24 05:25
no sudo, just:

```
service triplea-bot@01 status
:
:
service triplea-bot@04 status
```

bot55 => 500 range. So this is bots 501 through 504.
It should be same command on all bots with the "01" through "04" numbering, so on newark15, which is 100 range, those are bots 101-104 and would have same status commands.

**Comment by DanVanAtta** [comment] 2018-04-24 05:27
> Well Most of what i was running concerned attempting to update a bot server to the new engine using the above script. 

For the most part you will not have to worry about this   :grinning: 
We'll just check in the version number changes to [host_control.sh](https://github.com/triplea-game/infrastructure/blob/master/roles/host_control.sh); and the upgrades will happen automatically.

Lobby production server is last to be migrated to host control configuration, I just added the config for it and verified the DB migration part. When lobby activity is low we'll get that server under infrastructure control and then do an update to latest.

**Comment by prastle** [comment] 2018-04-24 05:30
Ok so all old service scripts work if sudo removed and using the new numbering system?

**Comment by prastle** [comment] 2018-04-24 05:30
Either way the reason it was nice to be able to update one bot server only was for testing before committing to all of them at once.

**Comment by DanVanAtta** [comment] 2018-04-24 16:12
well, we now have an auto-updating prerelease lobby with a bot attached, so we'll be able to test that way. We can also control the game engine version per server; while not ideal to mix bot versions that is a possibility.

**Comment by DanVanAtta** [comment] 2018-05-17 02:39
Did you ever get a direct answer on how to update bot servers @prastle ?

**Comment by prastle** [comment] 2018-05-17 02:41
@DanVanAtta Updating no.  Rest seems to be working now ty.

**Comment by DanVanAtta** [comment] 2018-05-17 02:46
You would update the version number in this file/line: https://github.com/triplea-game/infrastructure/blob/master/roles/host_control.sh#L26

Right now lobby + bot version are tied together, we can undo that readily but would need a reason/policy first. We should discuss in more detail how we manage bot software versioning so we can stay on the same page and ensure things stay easily managed.

**Comment by DanVanAtta** [comment] 2018-05-17 02:49
With: https://github.com/triplea-game/infrastructure/pull/52, the versioning makes more sense; and the bot and lobby versions would be decoupled. So after #52 is merged you literally just change the version number in the one place in the `host_control.sh` file, and 5 minutes later the bots will start upgrading. You should see them reporting new versions in the gitter system reporting room after they pick up the updates.

**Comment by prastle** [comment] 2018-05-17 02:51
Ok except that takes a pr and a commit.  Old days did not.  I can't commit.  Just you 4.  Either way all good.  At least they can be stopped and restarted again so any new maps can be added.   I should have clarified that as the real ?

**Comment by DanVanAtta** [comment] 2018-05-17 02:54
> Ok except that takes a pr and a commit

That is by design, anyone can cut the PR and propose it. We should be reviewing and merging each others PRs. For now we're breaking in the process and the other folks are relatively busy... I could see us turning on a requirement that at least one other person approve any changes before they are merged. In that system we could grant write access to many more people, that I think *is* the plan for at least this repo.

**Comment by DanVanAtta** [comment] 2018-05-17 02:54
> I guess they just need a restart to take effect or does the chron job handle that as well?

Restart is still manual, the cron does not know when the bot is empty. I created this ticket for us to avoid that manual restart: https://github.com/triplea-game/triplea/issues/3429

**Comment by prastle** [comment] 2018-05-17 02:55
Example a new map released today which ron merged
So will the chron job pick that up?

**Comment by DanVanAtta** [comment] 2018-05-17 02:55
check if it does please. As far as I know it would not and needs restarts across all bots.

**Comment by prastle** [comment] 2018-05-17 02:56
kk

**Comment by prastle** [comment] 2018-05-17 03:05
@DanVanAtta  yes it is picking them up on a restart.  You are correct.  But not from chron I guess.  402 I restarted and has the new map 404 does not.

**Comment by DanVanAtta** [comment] 2018-05-17 04:37
Thanks.

Does the bot numbering make sense as well?

Each bot has 01-04 on it. Each server is number, 1 through 6 (or 7?)

So 101 will be bot instance 01 running on server 1.
Server 303 would be bot instance 03 running on server 3. (ie: `service triplea-bot@03 status`)

**Comment by DanVanAtta** [comment] 2018-05-17 17:05
I'll go ahead and close this issue down, please re-open or create a new one if you've any questions at all

**Closed by DanVanAtta** 2018-05-17 17:05 UTC
